name: Release and Push to Central

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for tagging

      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Cache SonarCloud packages
        uses: actions/cache@v3  # ✅ Updated from v1 to v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3  # ✅ Updated from v1 to v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Create settings.xml file
        run: echo "$MAVEN_SETTINGS_XML" > ~/.m2/settings.xml
        env:
          MAVEN_SETTINGS_XML: ${{ vars.VAR_MAVEN_SETTINGS_XML }}

      - name: Debug `settings.xml`
        run: cat ~/.m2/settings.xml

      - name: Configure Git user
        run: |
          git config user.email "abhijeet.techrepo@gmail.com"
          git config user.name "abhijeet.techrepo"
          git pull origin master

      - name: release:prepare
        run: mvn -B release:prepare

      - name: release:perform
        run: mvn -B release:perform
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Tags
        run: |
          git push --tags
          git push origin master
